### PR TITLE
Feature / Content Mode for Images alongside Aspect Ratio Modifier

### PR DESCRIPTION
**Pull request by markstamer**
This PR adds the possibility to control the content mode for images alongside the aspect ratio modifier similar to SwiftUIs API. 

See Issue https://github.com/twostraws/Ignite/issues/89

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! This is just a quick message to apologize for taking so long to get to this – I really appreciate your work, I'm just really overloaded with the after effects of moving house! I'll get to it all this week, for sure. Thank you for your patience!

**Comment by twostraws** [comment]
This is perfect – thank you! Would it be okay to add you as a collaborator to the project? It wouldn't affect the way you do your current PRs, but it would allow you to review and merge PRs from others if you wanted.

**Comment by markstamer** [comment]
> Would it be okay to add you as a collaborator to the project?

First of all, I was on holiday for a couple of weeks but I'm back now! Sure, I would like to be a collaborator. 👍

**Comment by vdhamer** [comment]
Mark:

Any chance of getting sample code for an Image, in a specified aspect ratio, specified fill mode? I couldn't get the .aspectratio modifier to work on an Image type.

Error: `Argument type 'some BlockElement' does not conform to expected type 'InlineElement'`

BTW Issue #89 is still labelled open. It can probably be closed.

Peter (in The Netherlands)

**Comment by markstamer** [comment]
> Any chance of getting sample code for an Image, in a specified aspect ratio, specified fill mode? I couldn't get the .aspectratio modifier to work on an Image type.

The new modifier only works on an Image type. So make sure you modifiers in between the image and the aspect ratio modifier all return in image. This for example works for me: 

```swift
Image(decorative: "/images/profile.jpeg")
            .resizable()
            .cornerRadius(8)
            .aspectRatio(.square, contentMode: .fill)
```

> BTW Issue #89 is still labelled open. It can probably be closed.

Thanks. Done :)

**Comment by vdhamer** [comment]
> The new modifier only works on an Image type. 
> So make sure you modifiers in between the image and the aspect ratio modifier all return in image. 

Your sample code indeed works. But it turns out that my problem was because I had wrapped an Image in a Link(). Which made sense to me because HTML certainly allows you to nest <a href=...>  </a>.

I ended up replacing Link(Image.modifiers) by Image.modifiers.onClick() as you recommended in #99 (working code there).  Thanks for both parts of the solution.

**Pull request merged**
