### PR TITLE
Swift 6

### PR DESCRIPTION
**Pull request by dl-alexandre**
This making a few objects sendable including
- Action
- ShowModal
    - Option
- ContentPosition
- ContentAlignment
- MetaLink
- MetaTag
- Event
- FeedConfiguration
    - ContentMode
    - FeedImage
- UnitPoint
- AttributeValue
- Color
- CoreAttributes
- DiagonalEdge
- Edge

The Version String is also preferably `let` + Updated for current v0.2.1

### CODE REVIEW

**Comment by twostraws** [comment]
Thank you – this looks great! Almost all the changes look good, but do we *need* to bump the Swift tools version number? It would restrict Ignite to folks using Swift 6 or later, which is far from everyone at this point.

**Comment by twostraws** [comment]
I'm referring to someone who wants to build Ignite as a standalone project, who doesn't have Swift 6.

**Comment by dl-alexandre** [comment]
Understandable, Package.swift adjustments should be handled by you.

**Comment by twostraws** [comment]
Thank you! Once we actually need some Swift 6 features we can bump the version up. Until then, using an older swift-tools version should allow more people to use Ignite.

**Pull request merged**
