### PR TITLE
Update BootstrapOptions.swift

### PR DESCRIPTION
**Pull request by dl-alexandre**
Typo JavasScript -> Javascript

### CODE REVIEW

**Comment by dl-alexandre** [comment]
Failed Test Cases are now fixed, also attached

**Comment by twostraws** [comment]
This is a very hard change to review, because your editor has scattered tiny changes throughout – just take a look at the Files Changed tab here in GitHub, and you'll see what I mean. Could you please revise it?

**Comment by dl-alexandre** [comment]
Please review hiding whitespace (also from within the File Changed tab) as formatting adjustments make up most audio.swift changes.

**Comment by dl-alexandre** [comment]
Screenshot 2024-09-06 at 7 05 36 AM

**Comment by twostraws** [comment]
Alternatively, could you please run SwiftLint on your code and correct the new warnings there before submitting? We have the rules in place to help keep our code in order, and hiding whitespace isn't really solving that.

**Comment by dl-alexandre** [comment]
Definitely, my mistake

**Comment by dl-alexandre** [comment]
I see my issue was not including whitespace-only lines from within Xcode Settings. Also a function had to be broken into a dictionary. Thanks for the direction

**Comment by dl-alexandre** [comment]
I hope this isn't an overwhelming amount of changes in a single commit.

**Comment by twostraws** [comment]
I'm going to merge this now, thank you!

**Pull request merged**
