### PR TITLE
Added a table with links to website and repository made with Ignite

### PR DESCRIPTION
**Pull request by jcalderita**
This table is intended for people using Ignite to share their websites and view how others have built theirs.

### CODE REVIEW

**Comment by vdhamer** [comment]
What if the table becomes big (say 100-1000 rows):
- Volunteer to process the pull requests to quickly get them off the PR list?
- Entries must be open source? I think you assume that, but not all GitHub projects are OpenSource.
- Commercial websites allowed? Probably difficult if the answer is no.
- Distinguish between basic layout-and-data in Swift and those that only hardcode the layout in Swift syntax and use Swift code to pull in the data? See readme of unfinished [vdhamer/Photo-Club-Hub-HTML](https://github.com/vdhamer/Photo-Club-Hub-HTML)

**Comment by jcalderita** [comment]
I was thinking of adding this table for people who want to share their sites made with Ignite and others can see how they have used Ignite.
We could make another markdown for the site table and link it in the README, so it doesn't matter how big it is.
I think that all the projects in this list should be OpenSource but whatever you want.

**Comment by vdhamer** [comment]
> We could make another markdown for the site table and link it in the README, so it doesn't matter how big it is.

Sounds ok to me, but I am just a user. I guess a used-by table would need to be in a separate repo to void spamming the Pull Requests here?

**Comment by jcalderita** [comment]
> > We could make another markdown for the site table and link it in the README, so it doesn't matter how big it is.
> 
> Sounds ok to me, but I am just a user. I guess a used-by table would need to be in a separate repo to void spamming the Pull Requests here?

I agree with you, it's a great idea, a separate repository with just a link markdown and all pull request to add a new row.

Thank you.

**Comment by markstamer** [comment]
Great idea. Should we close this PR then?

**Comment by jcalderita** [comment]
> Great idea. Should we close this PR then?

Okay, so shall we open an issue?

**Comment by markstamer** [comment]
> Okay, so shall we open an issue?

I don't think it is a concern of this repository but it definitely would be nice to be discoverable from here. Maybe let's leave this issue open until @twostraws sees it. In my opinion you can go ahead and create such a repository and create a PR to add it to the README to make it visible.

**Comment by jcalderita** [comment]
Done

**Comment by vdhamer** [comment]
Once you get a green light from twostraws you are good to go to set up the mini-repo. I can be your wingman 🛩️ if you want. I can certainly provide a row. And will probably bug you for extra columns _if_ the table grows big. The problem with extra columns is that they are overkill for a small table. But need updating when added later 😏

**Comment by twostraws** [comment]
I think this is a lovely idea! I'm commenting here rather than the other PR, because there are already some important points made here.

First: I think this is a great idea! I'd be happy to feature sites that build with Ignite, and I think it would serve as inspiration for other folks too.

My views on what you've said:

> Volunteer to process the pull requests to quickly get them off the PR list?

Both @markstamer and I can merge these in easily, and as more folks build up commit history hopefully we can add some more contributors to the repository.

> Entries must be open source? I think you assume that, but not all GitHub projects are OpenSource.

I'd be okay with entries not being open source, but I'd also be happy to display the table so that open-source get some kind of marker / icon / link.

> Commercial websites allowed? Probably difficult if the answer is no.

I'm happy with commercial websites.

> Distinguish between basic layout-and-data in Swift and those that only hardcode the layout in Swift syntax and use Swift code to pull in the data?

I'm not sure this would add much…?

> Sounds ok to me, but I am just a user. I guess a used-by table would need to be in a separate repo to avoid spamming the Pull Requests here?

If it actually gets to the point that there really are that many PRs, it would be a lovely problem to have!

Anyway, I'm happy to put this list right here on the main repo README. Would that be okay with you folks?

The only thing I'd add is that we ask folks to add new links to the bottom, with the exception of anyone who shipped a site that predates this PR – there were a handful of very early adopters, and if they want to add their site here I think their bravery earned the the right to go at the top 😅

**Comment by vdhamer** [comment]
Agree.

Sent from my iPhone

On 18 Sep 2024, at 16:53, Jorge Calderita ***@***.***> wrote:

﻿

Everything seems perfect to me, I close the other pull request.
And let the pioneers be the first.
Thanks for everything.

**Comment by twostraws** [comment]
I can't re-open this pull request – could you do so, so I can merge it? Thank you!

**Comment by jcalderita** [comment]
Done

**Comment by twostraws** [comment]
Thank you!

**Pull request merged**
