### PR TITLE
Cleanup of URL-SelectDirectories.swift

### PR DESCRIPTION
**Pull request by vdhamer**
- Cleanup of URL-SelectDirectories (Fix: #135)
- SwiftLint 0.57.0 gives errors. See
    - [optional_string_data_conversion](https://github.com/realm/SwiftLint/issues/5785)
    - https://www.hackingwithswift.com/example-code/language/how-to-convert-data-to-a-string

### CODE REVIEW

**Comment by twostraws** [comment]
Is this good to merge?

**Comment by vdhamer** [comment]
Is this good to merge?

I have been using this branch for weeks now in my own project, and haven’t run into issues.

But I would reject the following of my own changes...

[Screenshot 2024-11-11 at 11.36.00 PM.png]
… because it looks more like a note to myself. It seems more confusing than helpful. Sorry.

A summary of the Pull Request changes:

  *   Cosmetics:
     *   Better comments on what selectDirectories(from:) is doing. In particular because of the 2 modes (executable package, include-able package).
     *   Renamed struct holding Source directory and Build directory for clarity: SourceBuildDirectories > SourceAndBuildDirectories.
     *   Fixed a typo in a comment (used to generate documentation).
  *   Fixes
     *   Fixed a compiler complaint about async requiring at least iOS 13. The entire package tends to have this problem if you run Ignite as an executable package (I don’t in my project). So there are more of these errors - somebody has grumbled about that before. You might want to fix the version compatibility at the Package level rather than my fix for a single function call).
     *   Fixed a SwiftLint complaint about fallibility of String(decoding:as:). Apparently debatable SwiftLint rule.
     *   Fixed a unit test where the function’s signature was probably changed, but the unit test was not updated.

There is indeed still another failing unit test. I didn’t cause that. I believe PR #138 (by harlanhaskins, an Apple sw engineer) is about something else but includes a fix for your tests.
<https://github.com/twostraws/Ignite/pull/138>
[138.png]
Ensure soft breaks in Markdown result in spaces in the resulting HTML by harlanhaskins · Pull Request #138 · twostraws/Ignite<https://github.com/twostraws/Ignite/pull/138>
github.com<https://github.com/twostraws/Ignite/pull/138>

About the iOS Target version (Xcode 16.2 beta 2):

[Screenshot 2024-11-12 at 12.19.47 AM.png]

**Comment by twostraws** [comment]
I'm not seeing the screenshot, I'm afraid. Anyway, please get the code exactly where you want it, including merging in any changes from the current main branch, then I'll merge. Thank you!

**Comment by vdhamer** [comment]
Will do.

Sent from my iPhone

On 12 Nov 2024, at 15:26, Paul Hudson ***@***.***> wrote:

﻿

I'm not seeing the screenshot, I'm afraid. Anyway, please get the code exactly where you want it, including merging in any changes from the current main branch, then I'll merge. Thank you!

**Comment by vdhamer** [comment]
Will replace this PR with a new PR (baseline has changed a lot).

**Pull request closed without merging**
