### PR TITLE
Streamline `Font` implementation...

### PR DESCRIPTION
**Pull request by JPToroDev**
Streamline `Font` implementation. Add `FontModifier` to apply fonts at the view level. Fix various bugs across font modifiers.

### CODE REVIEW

**Comment by twostraws** [comment]
This needs to be updated for the latest changes. Please make sure you resolve all SwiftLint issues after any changes.

**Comment by JPToroDev** [comment]
This is all set now.

**Comment by twostraws** [comment]
Thank you!

**Comment by twostraws** [comment]
Could you check this for build errors?

**Comment by JPToroDev** [comment]
I see the error—don't know why the compiler missed it before. Will fix and create a PR for it.

**Pull request merged**
